image: registry.cqse.eu/cqse/latex

# make gradle artifacts cachable
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew clean dist
  artifacts:
    paths:
      - build
    expire_in: 1 week
