sudo: false
language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
- rm -fr $HOME/.gradle/caches/jars-3/*/buildSrc.jar
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  file_glob: true
  file:
    - build/distributions/fileupload-service-*.zip
  skip_cleanup: true
  tags: true
  api_key:
    secure: ZvooaLGdAUhgOlcQqDcy7BCkJsswWvHoA9EYv4U4fR45YQYJ+AmSQLl1H3i1+G+XR20PDQeTbg7EaW06e5EOgktTeKmm4u3vWYA4hf/Clc6c54crMRhqfPMmE9Og4bP26oCSrgFlhJW1PAP+trdW4Wa7vra5EfjDEAMmxUpCoFU0i5ZxTriWEBmUGL3OyWMwo/QtQQoUtIEVlthBQM81AekBupzE7mvHqaJOEBUBXZoiKnjLCQUVBWgBp0UNk7Nyr41WgDyhXAPs69tqcOYv7nkIQrlf6R0BtpQaAa0I2B3PCxPAwNn0zlWcpiYx8IhH8TySCuGecsGEoI7gYfNsF61LaXfVfzhJw+ncOzzbXAFV7eI7tKpS8mG/PIhbBrYjF1OEYtttUJS5gyxJP4PLNKyu6rYa8Hpt5Zh9lpFesxEB+THzoBU3FADNgSfDpMC0e/J+EgVaIRI4BGVnAtc/LwMWVcZ+qWCFJiV7UyJCBZtyRcAoMT0TEcHIvjWix2VvuBTDwUgg30uSa4z1wtQdsp+/cNnt4FZ8P0g+AFT7pv2/rswOf3SdPtDmLwO3dATRw5b9Wj0h4ufdlBqpHA+ZAd3u0F0B130FvgKycpw6T2wZ0sC4mWNlU9cOhfj5c3QOeCIpQ/9Rc13Zp7OvvczZHqawDvz58IlmwhkuTrE2Ivg=
  on:
    repo: cqse/fileupload-service
